_install:
  uv pip install -e .

# Runs the specified day
run day:
  @uv run python -m aoc_2021.day_{{day}}

# Runs the time measurements
time:
  @uv run python -m aoc_2021.time 2>/dev/null

# Runs the whole tests suite
test: _install
  uv run pytest

format:
  uv format
